MGMT-16873: Change pull secret as part of recert reconfiguration
rh-ecosystem-edge/recert pull request #100
Opened 2024-02-15 16:33 UTC by tsorya

Change pull secret in all machine configs
Change pull secret in mcd currentconfig and mcs files

2024-02-15 16:46 UTC, mresvanis commented
@tsorya can you run `cargo fmt` and then commit the changes again?

2024-02-15 16:57 UTC, tsorya commented
> @tsorya can you run `cargo fmt` and then commit the changes again?

done

2024-02-15 17:32 UTC, mresvanis commented
I think it would be great to add the new config arg in the test [script](https://github.com/rh-ecosystem-edge/recert/blob/main/run_seed.sh#L115-L131). WDYT?

2024-02-19 09:33 UTC, tsorya commented
> I think it would be great to add the new config arg in the test [script](https://github.com/rh-ecosystem-edge/recert/blob/main/run_seed.sh#L115-L131). WDYT?

sure just some test data? or should i allow setting real pull-secret?

2024-02-19 10:31 UTC, omertuc requested changes
Looks great! Thank you. A few small nits

2024-02-19 10:31 UTC, omertuc commented on src/ocp_postprocess/cluster_domain_rename/rename_utils.rs
> +pub(crate) fn override_machineconfig_source(machineconfig: &mut Value, new_source: &str, path: &str) -> Result<()> {
Can you create a `mod` called `utils` under `pull_secret_rename` and move this function there? This `rename_utils` `mod` is under `cluster_domain_rename` and is meant only for domain rename

2024-02-19 10:32 UTC, omertuc commented
> > I think it would be great to add the new config arg in the test [script](https://github.com/rh-ecosystem-edge/recert/blob/main/run_seed.sh?rgh-link-date=2024-02-19T09%3A33%3A39Z#L115-L131). WDYT?
> 
> sure just some test data? or should i allow setting real pull-secret?

Just some test data

2024-02-19 10:32 UTC, omertuc commented on src/ocp_postprocess/pull_secret_rename/filesystem_rename.rs
> +    join_all(file_utils::globvec(dir, "**/config.json")?.into_iter().map(|file_path| {
Actually we won't have the `kubelet` prefix since the user brings in the whole kubelet directory :(

2024-02-19 10:33 UTC, omertuc commented on src/ocp_postprocess/pull_secret_rename/filesystem_rename.rs
> +    join_all(file_utils::globvec(dir, "**/config.json")?.into_iter().map(|file_path| {
So before renaming a `config.json` file maybe make sure it looks like a pull secret, so in the future we don't accidentally modify other files that happen to be called `config.json`

2024-02-19 11:03 UTC, mresvanis commented
> > I think it would be great to add the new config arg in the test [script](https://github.com/rh-ecosystem-edge/recert/blob/main/run_seed.sh#L115-L131). WDYT?
> 
> sure just some test data? or should i allow setting real pull-secret?

I think a test pull-secret (something that looks like a pull-secret) would be great (according also to Omer's comment [here](https://github.com/rh-ecosystem-edge/recert/pull/100#discussion_r1494342966)).

2024-02-19 11:48 UTC, tsorya commented on src/ocp_postprocess/pull_secret_rename/filesystem_rename.rs
> +    join_all(file_utils::globvec(dir, "**/config.json")?.into_iter().map(|file_path| {
Regarding mcdorig i am removing it from seed,just will not add it to archive

2024-02-19 11:49 UTC, omertuc commented on src/ocp_postprocess/pull_secret_rename/filesystem_rename.rs
> +    join_all(file_utils::globvec(dir, "**/config.json")?.into_iter().map(|file_path| {
Alright, I have no clue what that file does or what implications removing it has, so I can't weigh in here

2024-02-19 12:10 UTC, omertuc commented on src/ocp_postprocess/pull_secret_rename.rs
> +pub(crate) mod utils;
The utils module is only used by this pull secret module and its children, so `pub(crate)` is not necessary

```suggestion
mod utils;
```

2024-02-19 12:11 UTC, omertuc commented on run_seed.sh
> +		--pull-secret '{"auths":{"empty_registry":{"username":"empty","password":"empty","auth":"ZW1wdHk6ZW1wdHk=","email":""}}}' \
Can you also add it to the `WITH_CONFIG` yaml above?

2024-02-19 13:47 UTC, omertuc commented on etcddump
?

2024-02-19 14:07 UTC, omertuc commented on src/ocp_postprocess/pull_secret_rename/filesystem_rename.rs
> +            if dir_name == "kubelet" {
nit: avoid indentation

```suggestion
            if dir_name != "kubelet" {
                continue
            }
```

2024-02-19 14:29 UTC, omertuc commented
/test baremetalds-sno-recert-cluster-rename
/test e2e-aws-ovn-single-node-recert-serial
/test e2e-aws-ovn-single-node-recert-parallel

2024-02-19 16:54 UTC, tsorya commented
/retest

2024-02-20 10:24 UTC, merged

2024-02-20 10:25 UTC, tsorya commented
/override e2e-aws-ovn-single-node-recert-serial

2024-02-20 10:29 UTC, tsorya commented
/cherry-pick release-4.15

2024-02-20 10:36 UTC, tsorya commented
/cherry-pick release-4.15